const CnP_data = {
	extradata: ['', '', '', '', '', '', '', '', []],
	table_measurments: [
		['Size', '', '', '', '', '', '', '', '', '', ''],
		['Body length', '', '', '', '', '', '', '', '', ''],
		['Sleeve length', '', '', '', '', '', '', '', '', ''],
		['1/2 Chest', '', '', '', '', '', '', '', '', '', ''],
	],
	table_colourandcompotision: [
		['Colour', 'Composition', '', '', '', '', '', '', '', '', '', '', 'Count'],
		['', '', '', '', '', '', '', '', '', '', '', '', ''],
		['', '', '', '', '', '', '', '', '', '', '', '', ''],
		['', '', '', '', '', '', '', '', '', '', '', '', ''],
		['', '', '', '', '', '', '', '', '', '', '', '', ''],
		['', '', '', '', '', '', '', '', '', '', '', '', ''],
		['', '', '', '', '', '', '', '', '', '', '', '', ''],
		['', '', '', '', '', '', '', '', '', '', '', '', ''],
		['', '', '', '', '', '', '', '', '', '', '', '', ''],
		['Count', '', '', '', '', '', '', '', '', '', '', ''],
	],
	table_extrafabric: [
		['', '', '', '', ''],
		['', '', '', '', ''],
		['', '', '', '', ''],
		['', '', '', '', ''],
		['', '', '', '', ''],
		['', '', '', '', ''],
		['', '', '', '', ''],
		['G. Total', ''],
	],
	table_fabricfinishprocess: [['', ''], ['', ''], ['', ''], ['', ''], ['', '']],
	table_garmentapplication: [['', '', ''], ['', '', ''], ['', '', ''], ['', '', '']],
	table_accessoriesname: [
		['', '', ''],
		['', '', ''],
		['', '', ''],
		['', '', ''],
		['', '', ''],
		['', '', ''],
		['', '', ''],
		['', '', ''],
		['', '', ''],
		['', '', ''],
		['', '', ''],
		['', '', ''],
		['', '', ''],
		['', '', ''],
		['', '', ''],
		['', '', ''],
		['', '', ''],
		['', '', ''],
		['', '', ''],
		['', '', ''],
		['', '', ''],
		['', '', ''],
		['Count cost of accessories', ''],
	],
	table_currency: [
		['Exchange Rate', ''],
		['Count Yarn', ''],
		['Body consumption', ''],
		['Rib consumption', ''],
		['Lycra % Body', '', ''],
		['Lycra % Rib', '', ''],
		['Rib AOP quantity', ''],
	],
	table_price: [
		['Count yarn cost', '', '', ''],
		['Body knitting cost', '', '', ''],
		['Rib knitting cost', '', '', ''],
		['Dyeing cost', '', '', ''],
		['Lycra cost', '', '', ''],
		['Pitch finished cost', '', '', ''],
		['Brush finished cost', '', '', ''],
		['Tumble dry', '', '', ''],
		['AOP', '', '', ''],
		['Print', '', '', ''],
		['Sequence', '', '', ''],
		['Lather patch', '', '', ''],
		['Embroidery', '', '', ''],
		['Accessories', '', '', ''],
		['CM', '', '', ''],
		['Freight', '', '', ''],
		['Commercial cost', '', '', ''],
		['Extra cost 1', '', '', ''],
		['Extra cost 2', '', '', ''],
		['Extra cost 3', '', '', ''],
		['Buying commotion', '', '', ''],
		['Count', '', ''],
		['Order price (Colour)', '', 'Difference', ''],
		['Order price (White)', '', 'Difference', ''],
		['Order price (Black)', '', 'Difference', ''],
	],
	table_date: [
		['Yarn Required Date', ''],
		['Knitting Start Date', ''],
		['Knitting Close Date', ''],
		['Batch Received Date', ''],
		['Batch Delivery Date', ''],
		['Dyeing Start Date', ''],
		['Dyeing Close Date', ''],
		['Finished Fabrics Check Close', ''],
		['Finished Fabrics Inhouse', ''],
	],
}

export default CnP_data
