// Authentication
export const RESET_STATE = "RESET_STATE"
export const SAVEUSER = "SAVEUSER"

// Buyer
export const SAVE_COMPANIES = "SAVE_COMPANIES"
export const RESET_COMPANIES = "RESET_COMPANIES"
export const SAVE_BUYERS = "SAVE_BUYERS"
export const RESET_BUYER = "RESET_BUYER"

// Draft
export const SYNCTABLES = "SYNCTABLES"
export const SAVE_DRAFT = "SAVE_DRAFTS"
export const RESET_DRAFT = "RESET_DRAFT"
export const RESET_DRAFT_TABLE = "RESET_DRAFT_TABLE"
export const SAVE_DRAFTS = "SAVE_DRAFTS"
export const RESET_DRAFTS = "RESET_DRAFTS"
export const SAVE_DRAFT_METADATA = "SAVE_DRAFT_METADATA"
export const SAVE_DRAFT_TABLEDATA = "SAVE_DRAFT_TABLEDATA"

// Order
export const SAVE_ORDERS = "SAVE_ORDERS"
export const ADD_ORDERS = "ADD_ORDERS"
export const RESET_ORDERS = "RESET_ORDERS"
export const SAVE_ORDER = "SAVE_ORDER"
export const RESET_ORDER = "RESET_ORDER"
export const SAVE_SEARCHED_RESULT = "SAVE_SEARCHED_RESULT"
export const RESET_SEARCHED_RESULT = "RESET_SEARCHED_RESULT"
export const SAVE_ORDERS_COUNT = "SAVE_ORDERS_COUNT"
